"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { toast } from "sonner";

export default function EventForm({ initialData }: { initialData?: any }) {
  const router = useRouter();
  const [loading, setLoading] = useState(false);
  const [uploadingImage, setUploadingImage] = useState(false);
  const [imageFile, setImageFile] = useState<File | null>(null);
  
  const [aiLoading, setAiLoading] = useState(false);
  const [aiImageLoading, setAiImageLoading] = useState(false);
  const [aiImagePrompt, setAiImagePrompt] = useState("");
  const [tone, setTone] = useState("Tech & Visionary");
  const [imageStyle, setImageStyle] = useState("cinematic");
  
  const [formData, setFormData] = useState({
    title: initialData?.title || "",
    description: initialData?.description || "",
    category: initialData?.category || "",
    venue: initialData?.venue || "",
    startTime: initialData?.startTime ? new Date(initialData.startTime).toISOString().slice(0,16) : "",
    endTime: initialData?.endTime ? new Date(initialData.endTime).toISOString().slice(0,16) : "",
    price: initialData?.price || 0,
    capacity: initialData?.capacity || 100,
    status: initialData?.status || "DRAFT",
    bannerUrl: initialData?.bannerUrl || "",
    aiGeneratedDescription: initialData?.aiGeneratedDescription || false,
  });

  const handleAiEnhance = async () => {
    if (!formData.description || formData.description.length < 5) {
      toast.error("Please write a few draft notes before enhancing.");
      return;
    }
    setAiLoading(true);
    try {
      const res = await fetch("/api/ai/enhance-description", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ 
          description: formData.description,
          title: formData.title,
          category: formData.category,
          venue: formData.venue,
          tone
        }),
      });
      const data = await res.json();
      if (res.ok) {
        setFormData(prev => ({ 
          ...prev, 
          description: data.enhancedDescription,
          aiGeneratedDescription: true
        }));
        toast.success("Description enhanced with high-converting copywriting!");
      } else {
        toast.error(data.error || "Failed to enhance description");
      }
    } catch (err) {
      console.error(err);
      toast.error("Error contacting AI service");
    } finally {
      setAiLoading(false);
    }
  };

  const handleAiImageGenerate = async () => {
    if (!formData.title) {
      toast.error("Please enter an event title first to generate a banner.");
      return;
    }
    setAiImageLoading(true);
    try {
      const res = await fetch("/api/ai/generate-banner", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          title: formData.title,
          category: formData.category,
          description: formData.description,
          style: imageStyle,
        }),
      });

      const data = await res.json();
      if (res.ok && data.imageUrl) {
        setFormData(prev => ({ ...prev, bannerUrl: data.imageUrl }));
        if (data.aiPrompt) {
          setAiImagePrompt(data.aiPrompt);
        }
        setImageFile(null);
        toast.success("Studio-grade event banner generated by AI!");
      } else {
        toast.error(data.error || "Failed to generate banner");
      }
    } catch (err) {
      console.error(err);
      toast.error("Error generating banner image");
    } finally {
      setAiImageLoading(false);
    }
  };

  const handleSubmit = async (e: React.FormEvent, targetStatus?: "DRAFT" | "PUBLISHED" | "CANCELLED") => {
    if (e) e.preventDefault();
    setLoading(true);
    
    try {
      let finalBannerUrl = formData.bannerUrl;
      const statusToUse = targetStatus || formData.status;

      // Handle image upload first if a new file is selected
      if (imageFile) {
        setUploadingImage(true);
        try {
          const uploadFormData = new FormData();
          uploadFormData.append("file", imageFile);

          const uploadRes = await fetch("/api/upload", {
            method: "POST",
            body: uploadFormData,
          });

          if (!uploadRes.ok) {
            const errJson = await uploadRes.json().catch(() => null);
            throw new Error(errJson?.error || "Image upload failed");
          }

          const uploadData = await uploadRes.json();
          if (uploadData.url) {
            finalBannerUrl = uploadData.url;
            setFormData(prev => ({ ...prev, bannerUrl: uploadData.url }));
          }
        } catch (uploadErr: any) {
          console.error("Banner upload warning:", uploadErr);
          toast.error(`Image upload notice: ${uploadErr.message || "Failed to upload image"}. Continuing with event save.`);
        } finally {
          setUploadingImage(false);
        }
      }

      // Submit event data with normalized types
      const payload = { 
        ...formData, 
        price: Number(formData.price || 0),
        capacity: parseInt(String(formData.capacity || 100), 10),
        status: statusToUse, 
        bannerUrl: finalBannerUrl 
      };

      const endpoint = initialData ? `/api/events/${initialData.id}` : "/api/events";
      const method = initialData ? "PUT" : "POST";

      const res = await fetch(endpoint, {
        method,
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(payload),
      });

      if (res.ok) {
        toast.success(initialData ? "Event updated successfully" : "Event created successfully");
        router.push("/admin/events");
        router.refresh();
      } else {
        let errorMsg = "Failed to save event";
        try {
          const errData = await res.json();
          errorMsg = errData.error || errData.message || errorMsg;
        } catch {
          const text = await res.text();
          if (text) errorMsg = text;
        }
        toast.error(`Failed to save event: ${errorMsg}`);
      }
    } catch (err: any) {
      console.error("Error saving event:", err);
      toast.error(`Error saving event: ${err.message || "Network error. Please try again."}`);
      setUploadingImage(false);
    } finally {
      setLoading(false);
    }
  };

  const handleChange = (e: React.ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) => {
    const { name, value, type } = e.target;
    setFormData(prev => ({
      ...prev,
      [name]: type === "number" ? Number(value) : value,
      // If user edits description manually, remove AI flag
      ...(name === "description" ? { aiGeneratedDescription: false } : {})
    }));
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-6 bg-card-bg p-8 border border-card-border rounded shadow-xl text-foreground">
      <div className="grid grid-cols-2 gap-6">
        <div className="col-span-2">
          <div className="flex flex-wrap justify-between items-end gap-2 mb-2">
            <label className="block text-secondary text-sm font-bold">Event Banner Image</label>
            <div className="flex items-center gap-2">
              <select
                value={imageStyle}
                onChange={(e) => setImageStyle(e.target.value)}
                className="text-xs bg-background border border-card-border text-foreground px-2.5 py-1 rounded focus:outline-none focus:border-yellow"
                title="AI Banner Visual Style"
              >
                <option value="cinematic">🌟 Cinematic Studio</option>
                <option value="cyberpunk">⚡ Cyberpunk / Tech</option>
                <option value="minimalist3d">🎨 3D Glassmorphism</option>
                <option value="festival">🎆 Concert & Festival</option>
                <option value="editorial">🏛️ Minimalist Editorial</option>
              </select>
              <button
                type="button"
                onClick={handleAiImageGenerate}
                disabled={aiImageLoading}
                className="text-xs font-bold bg-background text-foreground px-3 py-1 rounded shadow-sm hover:scale-105 transition-transform disabled:opacity-50 flex items-center space-x-1 border border-card-border"
              >
                <span>🎨</span>
                <span>{aiImageLoading ? "Generating Flux Art..." : "Generate Banner (AI)"}</span>
              </button>
            </div>
          </div>
          <input 
            type="file" 
            accept="image/*"
            onChange={(e) => setImageFile(e.target.files?.[0] || null)}
            className="w-full bg-background border border-card-border rounded p-3 text-foreground focus:outline-none focus:border-yellow transition-colors file:mr-4 file:py-2 file:px-4 file:rounded file:border-0 file:text-sm file:font-bold file:bg-primary file:text-foreground hover:file:bg-secondary transition-colors"
          />
          {formData.bannerUrl && !imageFile && (
            <div className="mt-4">
              <div className="flex justify-between items-center mb-1">
                <p className="text-xs text-secondary">Banner preview:</p>
                <span className="text-[10px] font-mono text-secondary truncate max-w-xs">{formData.bannerUrl.split('?')[0]}</span>
              </div>
              <img src={formData.bannerUrl} alt="Banner Preview" className="w-full max-h-64 object-cover rounded-lg border border-card-border shadow-md" />
              {aiImagePrompt && (
                <div className="mt-2 p-2.5 rounded-lg bg-card-bg/60 border border-card-border text-xs text-secondary leading-relaxed">
                  <span className="font-bold text-primary mr-1">✨ AI Prompt:</span>
                  <span className="italic font-sans">"{aiImagePrompt}"</span>
                </div>
              )}
            </div>
          )}
        </div>

        <div className="col-span-2">
          <label className="block text-secondary text-sm font-bold mb-2">Event Title</label>
          <input 
            required type="text" name="title" value={formData.title} onChange={handleChange}
            className="w-full bg-background border border-card-border rounded p-3 text-foreground focus:outline-none focus:border-yellow transition-colors"
            placeholder="e.g. NextGen AI & Robotics Summit 2026"
          />
        </div>
        
        <div className="col-span-2 relative">
          <div className="flex flex-wrap justify-between items-end gap-2 mb-2">
            <label className="block text-secondary text-sm font-bold">Description</label>
            <div className="flex items-center gap-2">
              <select
                value={tone}
                onChange={(e) => setTone(e.target.value)}
                className="text-xs bg-background border border-card-border text-foreground px-2.5 py-1 rounded focus:outline-none focus:border-yellow"
                title="Copywriting Tone"
              >
                <option value="Tech & Visionary">💡 Tech & Visionary</option>
                <option value="High-Energy Festival">⚡ High-Energy Festival</option>
                <option value="Executive & VIP">👔 Executive & VIP</option>
                <option value="Community & Practical">🤝 Community & Practical</option>
              </select>
              <button
                type="button"
                onClick={handleAiEnhance}
                disabled={aiLoading}
                className="text-xs font-bold bg-background text-foreground px-3 py-1 rounded shadow-sm hover:scale-105 transition-transform disabled:opacity-50 flex items-center space-x-1 border border-card-border"
              >
                <span>✨</span>
                <span>{aiLoading ? "Writing Copy..." : "Enhance with AI"}</span>
              </button>
            </div>
          </div>
          <textarea 
            required name="description" value={formData.description} onChange={handleChange} rows={7}
            className="w-full bg-background border border-card-border rounded p-3 text-foreground focus:outline-none focus:border-yellow transition-colors font-sans text-sm"
            placeholder="Provide draft thoughts, bullet points, or overview and click 'Enhance with AI' to generate a full conversion-ready description..."
          />
          {formData.aiGeneratedDescription && (
            <span className="absolute bottom-4 right-4 text-xs font-bold text-primary bg-card-bg/90 border border-card-border px-2.5 py-1 rounded-md shadow-sm">
              ✨ AI Enhanced Copy
            </span>
          )}
        </div>

        <div>
          <label className="block text-secondary text-sm font-bold mb-2">Category</label>
          <input 
            required type="text" name="category" value={formData.category} onChange={handleChange}
            className="w-full bg-background border border-card-border rounded p-3 text-foreground focus:outline-none focus:border-yellow transition-colors"
          />
        </div>

        <div>
          <label className="block text-secondary text-sm font-bold mb-2">Venue</label>
          <input 
            required type="text" name="venue" value={formData.venue} onChange={handleChange}
            className="w-full bg-background border border-card-border rounded p-3 text-foreground focus:outline-none focus:border-yellow transition-colors"
          />
        </div>

        <div>
          <label className="block text-secondary text-sm font-bold mb-2">Start Time</label>
          <input 
            required type="datetime-local" name="startTime" value={formData.startTime} onChange={handleChange}
            className="w-full bg-background border border-card-border rounded p-3 text-foreground focus:outline-none focus:border-yellow transition-colors"
          />
        </div>

        <div>
          <label className="block text-secondary text-sm font-bold mb-2">End Time</label>
          <input 
            required type="datetime-local" name="endTime" value={formData.endTime} onChange={handleChange}
            className="w-full bg-background border border-card-border rounded p-3 text-foreground focus:outline-none focus:border-yellow transition-colors"
          />
        </div>

        <div>
          <label className="block text-secondary text-sm font-bold mb-2">Price (0 for free)</label>
          <input 
            required type="number" step="0.01" name="price" value={formData.price} onChange={handleChange}
            className="w-full bg-background border border-card-border rounded p-3 text-foreground focus:outline-none focus:border-yellow transition-colors"
          />
        </div>

        <div>
          <label className="block text-secondary text-sm font-bold mb-2">Capacity</label>
          <input 
            required type="number" name="capacity" value={formData.capacity} onChange={handleChange}
            className="w-full bg-background border border-card-border rounded p-3 text-foreground focus:outline-none focus:border-yellow transition-colors"
          />
        </div>
        
      </div>

      <div className="pt-8 border-t border-card-border/30 flex justify-end space-x-4">
        {formData.status === "PUBLISHED" ? (
          <>
            <button 
              type="button"
              onClick={(e) => {
                setFormData(prev => ({ ...prev, status: "DRAFT" }));
                handleSubmit(e, "DRAFT");
              }}
              disabled={loading || uploadingImage}
              className="bg-background border border-card-border hover:bg-foreground/5 text-foreground px-6 py-3 font-bold uppercase tracking-wider rounded-xl transition-all disabled:opacity-50 text-sm cursor-pointer"
            >
              {loading ? "Saving..." : "Revoke (Draft)"}
            </button>
            <button 
              type="button"
              onClick={(e) => {
                handleSubmit(e, "PUBLISHED");
              }}
              disabled={loading || uploadingImage}
              className="bg-primary text-foreground px-8 py-3 font-bold uppercase tracking-wider rounded-xl hover:scale-[1.02] active:scale-[0.98] transition-transform disabled:opacity-50 text-sm cursor-pointer shadow-lg hover:shadow-primary/20"
            >
              {uploadingImage ? "Uploading Image..." : loading ? "Updating..." : "Update Event"}
            </button>
          </>
        ) : (
          <>
            <button 
              type="button"
              onClick={(e) => {
                setFormData(prev => ({ ...prev, status: "DRAFT" }));
                handleSubmit(e, "DRAFT");
              }}
              disabled={loading || uploadingImage}
              className="bg-background border border-card-border hover:bg-foreground/5 text-foreground px-6 py-3 font-bold uppercase tracking-wider rounded-xl transition-all disabled:opacity-50 text-sm cursor-pointer"
            >
              {loading ? "Saving..." : "Save as Draft"}
            </button>
            <button 
              type="button"
              onClick={(e) => {
                setFormData(prev => ({ ...prev, status: "PUBLISHED" }));
                handleSubmit(e, "PUBLISHED");
              }}
              disabled={loading || uploadingImage}
              className="bg-primary text-foreground px-8 py-3 font-bold uppercase tracking-wider rounded-xl hover:scale-[1.02] active:scale-[0.98] transition-transform disabled:opacity-50 text-sm cursor-pointer shadow-lg hover:shadow-primary/20"
            >
              {uploadingImage ? "Uploading Image..." : loading ? "Publishing..." : "Publish Event"}
            </button>
          </>
        )}
      </div>
    </form>
  );
}
